export type SeoLocation = {
  name: string;
  slug: string;
  priority: boolean;
  nearby: string[];
};

const prioritySlugs = new Set([
  "uk",
  "england",
  "scotland",
  "wales",
  "northern-ireland",
  "london",
  "birmingham",
  "manchester",
  "liverpool",
  "leeds",
  "sheffield",
  "bristol",
  "nottingham",
  "leicester",
  "coventry",
  "newcastle",
  "cardiff",
  "edinburgh",
  "glasgow",
  "belfast",
  "kent",
  "medway",
  "chatham",
  "maidstone",
  "canterbury",
  "ashford",
  "croydon",
  "bromley",
  "greenwich"
]);

const nearbyBySlug: Record<string, string[]> = {
  uk: ["england", "scotland", "wales", "northern-ireland"],
  england: ["london", "birmingham", "manchester", "leeds"],
  scotland: ["edinburgh", "glasgow", "aberdeen", "dundee"],
  wales: ["cardiff", "swansea", "newport", "wrexham"],
  "northern-ireland": ["belfast", "derry", "lisburn", "newry"],
  london: ["central-london", "north-london", "south-london", "east-london", "west-london"],
  "greater-london": ["london", "central-london", "croydon", "bromley", "greenwich"],
  "central-london": ["westminster", "camden", "islington", "kensington"],
  "north-london": ["enfield", "harrow", "camden", "islington"],
  "south-london": ["croydon", "bromley", "brixton", "clapham"],
  "east-london": ["stratford", "ilford", "romford", "hackney"],
  "west-london": ["ealing", "hounslow", "uxbridge", "richmond"],
  birmingham: ["coventry", "wolverhampton", "leicester", "nottingham"],
  manchester: ["salford", "stockport", "oldham", "bolton"],
  liverpool: ["warrington", "chester", "wigan", "manchester"],
  leeds: ["wakefield", "huddersfield", "bradford", "york"],
  sheffield: ["rotherham", "barnsley", "doncaster", "nottingham"],
  bristol: ["bath", "cardiff", "gloucester", "swindon"],
  nottingham: ["derby", "leicester", "lincoln", "sheffield"],
  newcastle: ["sunderland", "middlesbrough", "york", "edinburgh"],
  cardiff: ["newport", "swansea", "bristol", "wrexham"],
  edinburgh: ["glasgow", "stirling", "perth", "dundee"],
  glasgow: ["edinburgh", "stirling", "perth", "inverness"],
  belfast: ["derry", "lisburn", "newry", "glasgow"],
  kent: ["medway", "maidstone", "canterbury", "ashford"],
  medway: ["chatham", "rochester", "gillingham", "rainham"],
  chatham: ["rochester", "gillingham", "rainham", "strood"],
  rochester: ["chatham", "gillingham", "strood", "walderslade"],
  gillingham: ["chatham", "rainham", "rochester", "hempstead"],
  maidstone: ["aylesford", "larkfield", "west-malling", "sittingbourne"],
  canterbury: ["whitstable", "herne-bay", "faversham", "ashford"],
  ashford: ["canterbury", "folkestone", "dover", "maidstone"],
  dartford: ["gravesend", "swanley", "bexley", "crayford"],
  bromley: ["orpington", "bexley", "croydon", "sidcup"],
  croydon: ["bromley", "epsom", "redhill", "reigate"]
};

const locationNames = [
  "UK",
  "England",
  "Scotland",
  "Wales",
  "Northern Ireland",
  "Kent",
  "Medway",
  "London",
  "Greater London",
  "Central London",
  "North London",
  "South London",
  "East London",
  "West London",
  "South East London",
  "South West London",
  "North West London",
  "North East London",
  "Birmingham",
  "Manchester",
  "Liverpool",
  "Leeds",
  "Sheffield",
  "Bristol",
  "Nottingham",
  "Leicester",
  "Coventry",
  "Bradford",
  "Newcastle",
  "Sunderland",
  "Wolverhampton",
  "Derby",
  "Stoke-on-Trent",
  "Southampton",
  "Portsmouth",
  "Brighton",
  "Plymouth",
  "Exeter",
  "Norwich",
  "Cambridge",
  "Oxford",
  "Reading",
  "Milton Keynes",
  "Luton",
  "Bedford",
  "Northampton",
  "Peterborough",
  "Swindon",
  "Gloucester",
  "Cheltenham",
  "Bournemouth",
  "Poole",
  "Bath",
  "York",
  "Hull",
  "Middlesbrough",
  "Preston",
  "Blackpool",
  "Bolton",
  "Wigan",
  "Warrington",
  "Chester",
  "Stockport",
  "Oldham",
  "Rochdale",
  "Salford",
  "Wakefield",
  "Huddersfield",
  "Halifax",
  "Doncaster",
  "Rotherham",
  "Barnsley",
  "Lincoln",
  "Grimsby",
  "Ipswich",
  "Colchester",
  "Southend-on-Sea",
  "Chelmsford",
  "Basildon",
  "Watford",
  "St Albans",
  "Hemel Hempstead",
  "Stevenage",
  "Harlow",
  "Guildford",
  "Woking",
  "Epsom",
  "Kingston upon Thames",
  "Croydon",
  "Bromley",
  "Bexley",
  "Greenwich",
  "Lewisham",
  "Dartford",
  "Gravesend",
  "Sevenoaks",
  "Tonbridge",
  "Tunbridge Wells",
  "Maidstone",
  "Chatham",
  "Rochester",
  "Gillingham",
  "Rainham",
  "Strood",
  "Walderslade",
  "Lordswood",
  "Hempstead",
  "Sittingbourne",
  "Faversham",
  "Canterbury",
  "Ashford",
  "Folkestone",
  "Dover",
  "Deal",
  "Ramsgate",
  "Margate",
  "Broadstairs",
  "Herne Bay",
  "Whitstable",
  "Aylesford",
  "Snodland",
  "West Malling",
  "Larkfield",
  "Borough Green",
  "Meopham",
  "Longfield",
  "Swanley",
  "Orpington",
  "Sidcup",
  "Welling",
  "Erith",
  "Crayford",
  "Eltham",
  "Blackheath",
  "Dulwich",
  "Brixton",
  "Clapham",
  "Wandsworth",
  "Putney",
  "Richmond",
  "Hammersmith",
  "Fulham",
  "Chelsea",
  "Kensington",
  "Westminster",
  "Camden",
  "Islington",
  "Hackney",
  "Stratford",
  "Ilford",
  "Romford",
  "Enfield",
  "Harrow",
  "Ealing",
  "Hounslow",
  "Uxbridge",
  "Hayes",
  "Slough",
  "Windsor",
  "Maidenhead",
  "Bracknell",
  "Basingstoke",
  "Winchester",
  "Fareham",
  "Gosport",
  "Chichester",
  "Worthing",
  "Eastbourne",
  "Hastings",
  "Crawley",
  "Horsham",
  "Redhill",
  "Reigate",
  "Dorking",
  "Cardiff",
  "Swansea",
  "Newport",
  "Wrexham",
  "Bangor",
  "Edinburgh",
  "Glasgow",
  "Aberdeen",
  "Dundee",
  "Inverness",
  "Stirling",
  "Perth",
  "Belfast",
  "Derry",
  "Lisburn",
  "Newry"
];

const londonAreaSlugs = new Set([
  "croydon",
  "bromley",
  "bexley",
  "greenwich",
  "lewisham",
  "orpington",
  "sidcup",
  "welling",
  "erith",
  "crayford",
  "eltham",
  "blackheath",
  "dulwich",
  "brixton",
  "clapham",
  "wandsworth",
  "putney",
  "richmond",
  "hammersmith",
  "fulham",
  "chelsea",
  "kensington",
  "westminster",
  "camden",
  "islington",
  "hackney",
  "stratford",
  "ilford",
  "romford",
  "enfield",
  "harrow",
  "ealing",
  "hounslow",
  "uxbridge",
  "hayes"
]);

const kentAndMedwaySlugs = new Set([
  "dartford",
  "gravesend",
  "sevenoaks",
  "tonbridge",
  "tunbridge-wells",
  "maidstone",
  "chatham",
  "rochester",
  "gillingham",
  "rainham",
  "strood",
  "walderslade",
  "lordswood",
  "hempstead",
  "sittingbourne",
  "faversham",
  "canterbury",
  "ashford",
  "folkestone",
  "dover",
  "deal",
  "ramsgate",
  "margate",
  "broadstairs",
  "herne-bay",
  "whitstable",
  "aylesford",
  "snodland",
  "west-malling",
  "larkfield",
  "borough-green",
  "meopham",
  "longfield",
  "swanley"
]);

const walesSlugs = new Set(["cardiff", "swansea", "newport", "wrexham", "bangor"]);
const scotlandSlugs = new Set(["edinburgh", "glasgow", "aberdeen", "dundee", "inverness", "stirling", "perth"]);
const northernIrelandSlugs = new Set(["belfast", "derry", "lisburn", "newry"]);

export const seoLocations: SeoLocation[] = locationNames.map((name) => {
  const slug = slugifyLocation(name);
  return {
    name,
    slug,
    priority: prioritySlugs.has(slug),
    nearby: nearbyBySlug[slug] ?? defaultNearby(slug)
  };
});

export function findSeoLocation(slug: string) {
  return seoLocations.find((location) => location.slug === slug);
}

function defaultNearby(slug: string) {
  if (slug.includes("london") || londonAreaSlugs.has(slug)) return ["london", "greater-london", "central-london"].filter((item) => item !== slug);
  if (kentAndMedwaySlugs.has(slug)) return ["chatham", "maidstone", "canterbury", "ashford"].filter((item) => item !== slug);
  if (walesSlugs.has(slug)) return ["cardiff", "swansea", "newport"].filter((item) => item !== slug);
  if (scotlandSlugs.has(slug)) return ["edinburgh", "glasgow", "aberdeen"].filter((item) => item !== slug);
  if (northernIrelandSlugs.has(slug)) return ["belfast", "derry", "lisburn"].filter((item) => item !== slug);
  return ["london", "birmingham", "manchester"].filter((item) => item !== slug);
}

function slugifyLocation(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
