export const SUBJECTS = [
  "Maths",
  "English",
  "English Language",
  "English Literature",
  "Science",
  "Combined Science",
  "Triple Science",
  "Biology",
  "Chemistry",
  "Physics",
  "11 Plus",
  "11+",
  "Entrance Exams",
  "Grammar School Entrance",
  "Private School Entrance",
  "Verbal Reasoning",
  "Non-Verbal Reasoning",
  "Creative Writing",
  "Reading",
  "Spelling",
  "Phonics",
  "Primary Maths",
  "Primary English",
  "KS1",
  "KS2",
  "KS3",
  "GCSE",
  "A-Level",
  "Further Maths",
  "Statistics",
  "Mechanics",
  "Computer Science",
  "ICT",
  "Coding",
  "Programming",
  "Python",
  "JavaScript",
  "Web Development",
  "French",
  "Spanish",
  "German",
  "Italian",
  "Latin",
  "Classical Civilisation",
  "History",
  "Geography",
  "Religious Studies",
  "Philosophy",
  "Sociology",
  "Psychology",
  "Economics",
  "Business Studies",
  "Accounting",
  "Politics",
  "Law",
  "Media Studies",
  "Drama",
  "Music",
  "Art",
  "Design Technology",
  "Food Technology",
  "PE",
  "Sports Science",
  "Health and Social Care",
  "Childcare",
  "Functional Skills Maths",
  "Functional Skills English",
  "Adult Learning",
  "English as a Foreign Language",
  "ESOL",
  "EAL",
  "IELTS",
  "University Admissions",
  "Oxbridge Admissions",
  "UCAS Support",
  "Personal Statement Support",
  "Medical School Admissions",
  "Dentistry Admissions",
  "LNAT",
  "BMAT",
  "UCAT",
  "SATs",
  "Year 6 SATs",
  "Scottish Nationals",
  "Scottish Highers",
  "IB",
  "International Baccalaureate",
  "iGCSE",
  "T-Level Support",
  "BTEC Support",
  "SEN",
  "SEND",
  "Dyslexia",
  "Dyspraxia",
  "ADHD",
  "Autism",
  "ASD",
  "Homeschooling Support",
  "Exam Technique",
  "Study Skills",
  "Revision Skills"
] as const;

export const LEVELS = [
  "Primary",
  "Primary school",
  "KS1",
  "Key Stage 1",
  "KS2",
  "Key Stage 2",
  "Year 1",
  "Year 2",
  "Year 3",
  "Year 4",
  "Year 5",
  "Year 6",
  "SATs",
  "Year 6 SATs",
  "11 Plus",
  "11+",
  "Entrance Exams",
  "Grammar School Entrance",
  "Private School Entrance",
  "Secondary School",
  "KS3",
  "Key Stage 3",
  "Year 7",
  "Year 8",
  "Year 9",
  "GCSE",
  "iGCSE",
  "Year 10",
  "Year 11",
  "A-Level",
  "AS-Level",
  "Sixth Form",
  "Year 12",
  "Year 13",
  "IB",
  "International Baccalaureate",
  "BTEC",
  "T-Level",
  "Functional Skills",
  "Adult Learner",
  "University",
  "Degree Level",
  "Beginner",
  "Intermediate",
  "Advanced",
  "Homeschooling",
  "SEN",
  "SEND"
] as const;

export const DIRECTORY_DISCLAIMER =
  "TuitionList is a directory only. Tutors and tuition providers listed on TuitionList are independent and are not employed by TuitionList. We do not guarantee the quality, suitability, availability, qualifications, DBS status, safeguarding arrangements, or outcomes of any tutor. Parents, carers, and students are responsible for carrying out their own checks before arranging tuition.";

export const PROFILE_DISCLAIMER =
  "TuitionList is a directory only. Tutors and tuition providers listed on TuitionList are independent and are not employed by TuitionList. We do not guarantee the quality, suitability, availability, qualifications, DBS status, safeguarding arrangements, or outcomes of any tutor. Parents, carers, and students are responsible for carrying out their own checks before arranging tuition.";

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
