with subject_values(name) as (
  select unnest(array[
    'Maths',
    'English',
    'English Language',
    'English Literature',
    'Science',
    'Combined Science',
    'Triple Science',
    'Biology',
    'Chemistry',
    'Physics',
    '11 Plus',
    '11+',
    'Entrance Exams',
    'Grammar School Entrance',
    'Private School Entrance',
    'Verbal Reasoning',
    'Non-Verbal Reasoning',
    'Creative Writing',
    'Reading',
    'Spelling',
    'Phonics',
    'Primary Maths',
    'Primary English',
    'KS1',
    'KS2',
    'KS3',
    'GCSE',
    'A-Level',
    'Further Maths',
    'Statistics',
    'Mechanics',
    'Computer Science',
    'ICT',
    'Coding',
    'Programming',
    'Python',
    'JavaScript',
    'Web Development',
    'French',
    'Spanish',
    'German',
    'Italian',
    'Latin',
    'Classical Civilisation',
    'History',
    'Geography',
    'Religious Studies',
    'Philosophy',
    'Sociology',
    'Psychology',
    'Economics',
    'Business Studies',
    'Accounting',
    'Politics',
    'Law',
    'Media Studies',
    'Drama',
    'Music',
    'Art',
    'Design Technology',
    'Food Technology',
    'PE',
    'Sports Science',
    'Health and Social Care',
    'Childcare',
    'Functional Skills Maths',
    'Functional Skills English',
    'Adult Learning',
    'English as a Foreign Language',
    'ESOL',
    'EAL',
    'IELTS',
    'University Admissions',
    'Oxbridge Admissions',
    'UCAS Support',
    'Personal Statement Support',
    'Medical School Admissions',
    'Dentistry Admissions',
    'LNAT',
    'BMAT',
    'UCAT',
    'SATs',
    'Year 6 SATs',
    'Scottish Nationals',
    'Scottish Highers',
    'IB',
    'International Baccalaureate',
    'iGCSE',
    'T-Level Support',
    'BTEC Support',
    'SEN',
    'SEND',
    'Dyslexia',
    'Dyspraxia',
    'ADHD',
    'Autism',
    'ASD',
    'Homeschooling Support',
    'Exam Technique',
    'Study Skills',
    'Revision Skills'
  ]::text[])
)
insert into public.subjects (name, slug)
select
  name,
  trim(both '-' from lower(regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g')))
from subject_values
on conflict (slug) do update
set name = excluded.name;

with level_values(name) as (
  select unnest(array[
    'Primary',
    'Primary school',
    'KS1',
    'Key Stage 1',
    'KS2',
    'Key Stage 2',
    'Year 1',
    'Year 2',
    'Year 3',
    'Year 4',
    'Year 5',
    'Year 6',
    'SATs',
    'Year 6 SATs',
    '11 Plus',
    '11+',
    'Entrance Exams',
    'Grammar School Entrance',
    'Private School Entrance',
    'Secondary School',
    'KS3',
    'Key Stage 3',
    'Year 7',
    'Year 8',
    'Year 9',
    'GCSE',
    'iGCSE',
    'Year 10',
    'Year 11',
    'A-Level',
    'AS-Level',
    'Sixth Form',
    'Year 12',
    'Year 13',
    'IB',
    'International Baccalaureate',
    'BTEC',
    'T-Level',
    'Functional Skills',
    'Adult Learner',
    'University',
    'Degree Level',
    'Beginner',
    'Intermediate',
    'Advanced',
    'Homeschooling',
    'SEN',
    'SEND'
  ]::text[])
)
insert into public.levels (name, slug)
select
  name,
  trim(both '-' from lower(regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g')))
from level_values
on conflict (slug) do update
set name = excluded.name;
